language: python
python:
  - "3.6"
  - "3.7"
  - "3.7"
  - "3.8"
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build

cache:
  pip: true
  directories:
    - .venv

env:
  global:
    - RANDOM_SEED=0
    - BOTO_CONFIG=/dev/null  # https://github.com/travis-ci/travis-ci/issues/7940

before_install:
  - "sudo apt-get install python3-tk"
  - python -m pip install -U --upgrade pip
  - python -m pip install -U  pipenv
  # Work around https://github.com/jaraco/zipp/issues/40.
  - python -m pip install -U zipp
  - make doctor

install:
  - make install

script:
  - make ci

after_success:
  - python -m pip install -U coveralls scrutinizer-ocular
  - coveralls
  - ocular

notifications:
  email:
    on_success: never
    on_failure: never
