language: python
python:
  - "3.6"
  - "3.7"
  - "3.7"
  - "3.8"
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build

cache:
  pip: true
  directories:
    - .venv

env:
  global:
    - RANDOM_SEED=0
    - BOTO_CONFIG=/dev/null  # https://github.com/travis-ci/travis-ci/issues/7940

before_install:
  - "sudo apt-get install python3-tk"
  - pip install --upgrade pip
  - pip install pipenv
  - make doctor

install:
  - make install

script:
  - make ci

after_success:
  - pip install coveralls scrutinizer-ocular
  - coveralls
  - ocular

notifications:
  email:
    on_success: never
    on_failure: never
