dist: xenial   # required for Python >= 3.7
language: python
python:
  - "3.5"
  - "3.5-dev"  # 3.5 development branch
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
  - "3.7"
  - "3.7-dev"  # 3.7 development branch
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build

cache:
  pip: true
  directories:
    - .venv

env:
  global:
    - RANDOM_SEED=0
    - BOTO_CONFIG=/dev/null  # https://github.com/travis-ci/travis-ci/issues/7940

before_install:
  - sudo apt-get install python3-tk
  - pip install pipenv
  - make doctor

install:
  - make install

script:
  - make check
  - make test

after_success:
  - pip install coveralls scrutinizer-ocular
  - coveralls
  - ocular

notifications:
  email:
    on_success: never
    on_failure: never
