site_name: Ethically
site_description: Python Package for Designing, Auditing and Adjusting the Ethics of AI Systems.
site_author: Shlomi Hod
repo_url: https://github.com/ethicallyAI/ethically

theme: readthedocs

pages:
- Home: index.md
- About:
  - Release Notes: about/changelog.md
  - Contributing: about/contributing.md
  - License: about/license.md
